KOTY: TcpServ Class Reference
TcpServ Class Reference
Responsible for creating a server robot connects to.
#include <tcpserv.hh>
Signals
void valueSharpChanged (int value)
valueSharpChanged informs about new data arrival
void valueTof1Changed (int value)
valueTof1Changed informs about new data arrival for sensor ToF1
void valueTof2Changed (int value)
valueTof2Changed informs about new data arrival for sensor ToF2
void valueXChanged (float value)
valueXChanged informs about new X coordinate data
void valueYChanged (float value)
valueYChanged informs about new Y coordinate data
void valueAngleChanged (float value)
valueAngleChanged informs about new angle data
void accelerationXChanged (float value)
accelerationXChanged informs about new acceleration data in X axis
void accelerationYChanged (float value)
accelerationXChanged informs about new acceleration data in X axis
void valueSpeedChanged (float value)
ValueSpeedChanged informs about new speed data data.
Public Member Functions
bool isActive () const
Checks if server is active.
void activateServer ()
Starts the server.
void deactivateServer ()
Stops the server.
TcpServ (QWidget *parent=nullptr)
Constructor for TcpServ class.
Private Slots
void newConnection ()
Slot to handle new incoming connections.
void Read_Data_From_Socket ()
Slot to read data from the socket.
void sendData ()
Slot to send data through the socket.
void Add_New_Client_Connection (QTcpSocket *s)
Slot to add a new client connection.
void sendDataToSocket (const QByteArray &data)
Slot to send data to a specific socket.
Private Attributes
QTcpServer * server
TCP server instance.
QLineEdit * xEdit
Line edit for X coordinate input.
QLineEdit * yEdit
Line edit for Y coordinate input.
QPushButton * sendButton
Button to send data.
QVector< QTcpSocket * > Client_Connection_List
List of client connections.
bool active
Detailed Description
Definition at line 24 of file tcpserv.hh.
Constructor & Destructor Documentation
TcpServ()
TcpServ::TcpServ (QWidget * parent = nullptr) explicit
Parameters
parent - pointer to parent widget, default is nullptr
Definition at line 6 of file tcpserv.cpp.
References newConnection(), and server.
Member Function Documentation
accelerationXChanged
void TcpServ::accelerationXChanged (float value) signal
Parameters
value - new y axis acceleration - float
accelerationYChanged
void TcpServ::accelerationYChanged (float value) signal
Parameters
value - new y axis acceleration - float
activateServer()
void TcpServ::activateServer ()
Definition at line 125 of file tcpserv.cpp.
References active.
Add_New_Client_Connection
void TcpServ::Add_New_Client_Connection (QTcpSocket * s) private slot
Parameters
s - pointer to the new QTcpSocket
Definition at line 84 of file tcpserv.cpp.
References Client_Connection_List, and Read_Data_From_Socket().
deactivateServer()
void TcpServ::deactivateServer ()
Definition at line 132 of file tcpserv.cpp.
References active.
isActive()
bool TcpServ::isActive () const
Definition at line 120 of file tcpserv.cpp.
References active.
newConnection
void TcpServ::newConnection () private slot
Definition at line 78 of file tcpserv.cpp.
References Add_New_Client_Connection(), and server.
Read_Data_From_Socket
void TcpServ::Read_Data_From_Socket () private slot
Definition at line 32 of file tcpserv.cpp.
References accelerationXChanged(), accelerationYChanged(), valueAngleChanged(), valueSharpChanged(), valueSpeedChanged(), valueTof1Changed(), valueTof2Changed(), valueXChanged(), and valueYChanged().
sendData
void TcpServ::sendData () private slot
Definition at line 106 of file tcpserv.cpp.
References sendDataToSocket(), xEdit, and yEdit.
sendDataToSocket
void TcpServ::sendDataToSocket (const QByteArray & data) private slot
Parameters
data - data to send
Definition at line 97 of file tcpserv.cpp.
References Client_Connection_List.
valueAngleChanged
void TcpServ::valueAngleChanged (float value) signal
Parameters
value - new angle - float
valueSharpChanged
void TcpServ::valueSharpChanged (int value) signal
Parameters
value - new distance reading - int
valueSpeedChanged
void TcpServ::valueSpeedChanged (float value) signal
Parameters
value - new speed data - float
valueTof1Changed
void TcpServ::valueTof1Changed (int value) signal
Parameters
value - new distance reading - int
valueTof2Changed
void TcpServ::valueTof2Changed (int value) signal
Parameters
value - new distance reading - int
valueXChanged
void TcpServ::valueXChanged (float value) signal
Parameters
value - pew X coordinate - float
valueYChanged
void TcpServ::valueYChanged (float value) signal
Parameters
value - new Y coordinate - float
Member Data Documentation
active
bool TcpServ::active private
Definition at line 129 of file tcpserv.hh.
Client_Connection_List
QVector<QTcpSocket*> TcpServ::Client_Connection_List private
Definition at line 128 of file tcpserv.hh.
sendButton
QPushButton* TcpServ::sendButton private
Definition at line 127 of file tcpserv.hh.
server
QTcpServer* TcpServ::server private
Definition at line 124 of file tcpserv.hh.
xEdit
QLineEdit* TcpServ::xEdit private
Definition at line 125 of file tcpserv.hh.
yEdit
QLineEdit* TcpServ::yEdit private
Definition at line 126 of file tcpserv.hh.
The documentation for this class was generated from the following files:
tcpserv.hh
tcpserv.cpp