KOTY: Speedometer Class Reference
Speedometer Class Reference
Models the concept of a speedometer.
#include <speedometer.hh>
Public Slots
void setSpeedValue (float value)
Sets the speed.
Public Member Functions
Speedometer (QWidget *parent=nullptr)
void setSpeed (int speed)
setSpeed sets the speed
Protected Member Functions
void paintEvent (QPaintEvent *) override
paintEvent allows for the creation of the speedometer clock object
Private Slots
void updateNeedle ()
updateNeedle refreshes the position of the clock's needle
void sliderValueChanged (int value)
sliderValueChanged handles the slider's value change
Private Attributes
QTimer * m_timer
QSlider * m_speedSlider
int m_speed
double m_angle
Detailed Description
Definition at line 20 of file speedometer.hh.
Constructor & Destructor Documentation
Speedometer()
Speedometer::Speedometer (QWidget * parent = nullptr) explicit
Definition at line 7 of file speedometer.cpp.
References m_timer, and updateNeedle().
Member Function Documentation
paintEvent()
void Speedometer::paintEvent (QPaintEvent *) override protected
Definition at line 24 of file speedometer.cpp.
References m_angle.
setSpeed()
void Speedometer::setSpeed (int speed)
Parameters
speed - speed parameter
Definition at line 19 of file speedometer.cpp.
References m_speed.
setSpeedValue
void Speedometer::setSpeedValue (float value) slot
Parameters
value - the speed data from signal
Definition at line 89 of file speedometer.cpp.
References setSpeed().
sliderValueChanged
void Speedometer::sliderValueChanged (int value) private slot
Parameters
value - slider's value
Definition at line 84 of file speedometer.cpp.
References setSpeed().
updateNeedle
void Speedometer::updateNeedle () private slot
Definition at line 79 of file speedometer.cpp.
References m_angle, and m_speed.
Member Data Documentation
m_angle
double Speedometer::m_angle private
Definition at line 58 of file speedometer.hh.
m_speed
int Speedometer::m_speed private
Definition at line 57 of file speedometer.hh.
m_speedSlider
QSlider* Speedometer::m_speedSlider private
Definition at line 56 of file speedometer.hh.
m_timer
QTimer* Speedometer::m_timer private
Definition at line 55 of file speedometer.hh.
The documentation for this class was generated from the following files:
speedometer.hh
speedometer.cpp